name: Python Coverage

on:
  pull_request:
    branches:
      - main

permissions:
  pull-requests: write
  
jobs:
  python-coverage:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13
      - name: Install dependencies
        run: |
           python -m pip install --upgrade pip
           pip install ruff pytest
           if [ -f requirements.txt ]; then pip install -r requirements.txt; fi
      - name: Lint and format Python code with ruff
        run: |
         # Lint with the default set of ruff rules with GitHub Annotations
         ruff check --format=github --target-version=py39
         # Verify the code is properly formatted
         ruff format --diff --target-version=py39
      - name: Run tests and generate coverage details
        run: pytest --cov=src
      - name: Coverage comment
        uses: py-cov-action/python-coverage-comment-action@v3
        with:
          GITHUB_TOKEN: ${{ github.token }}
          MINIMUM_GREEN: 90
          MINIMUM_ORANGE: 70
      - name: Fail if below threshold
        run: coverage report --fail-under=90
